### ISSUE TITLE
Introduce official code-generated documentation for PHP and JS

### ISSUE THREAD

**Issue by askvortsov1** [flarum/docs#122]
It would be nice to convert http://api.flarum.dev/ into official documentation that we could reference from the vuepress docs.

**Comment by datitisev** [comment]
Reference in what whay? How would the official one differ from my unofficial one?

**Comment by askvortsov1** [comment]
It wouldn't differ, but we would want to keep it updated. And when I say reference, I mean we could link to docblocks from other parts of the documentation.

**Comment by datitisev** [comment]
>  I mean we could link to docblocks from other parts of the documentation.

Wouldn't this require some integration with vuepress? Or would it just be a link that goes to the API doc page?

**Comment by franzliedke** [comment]
Links would be fine, and that's what I was always hoping to have for the extenders (i.e. describe them shortly in the prose docs, and then link off to the API docs that have all the details thanks to docblocks).

@datitisev Oh, or were you worried about having versioned URLs and keeping them updated in the docs?
