### ISSUE TITLE
Is this repo deprecated?

### ISSUE THREAD

**Issue by gwillem** [flarum/docs#13]
I was creating a PR but then found out there is also https://github.com/flarum/flarum.github.io

**Comment by luceos** [comment]
No, this is the new documentation repository. It will be used for new releases.

**Comment by gwillem** [comment]
So where to submit PRs? This repo lags behind the other one, for example [there](https://github.com/flarum/flarum.github.io/blob/master/_docs/troubleshooting.md) and [here](https://github.com/flarum/docs/blob/master/user/troubleshooting.md).

**Comment by tobscure** [comment]
Submit to this repo, unless you're hoping for changes to go live in the short-term, in which case submit to both :)

**Comment by gwillem** [comment]
So when will this repo go live? My incentive to write docs is to help users right now, so perhaps I'm better off with the other one :)

**Comment by gwillem** [comment]
FWIW, in my experience, nobody will maintain docs in two places. So if you want to switch, I'd recommend a big bang conversion :boom:

**Comment by franzliedke** [comment]
@tobscure You're planning to integrate these docs into the revamped website, right?

**Comment by tobscure** [comment]
@franzliedke yes! When that will be, hard to say, hopefully within a month or two

**Comment by gwillem** [comment]
@tobscure Do you want help with this? Tap into community resources for peripheral components such as documentation? I'm sure people would get together to get this doc conversion done. For you to do: appoint coordinator & formulate objectives and constraints.

**Comment by luceos** [comment]
@gwillem we can use all the help we can get. If you're interested in picking up some documentation tasks, feel free to chat @jordanjay29 up on discord 👍
