### ISSUE TITLE
Order of parameters to javascript Extend.Routes.add does not match reality

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/docs#130]
At https://docs.flarum.org/extend/routes.html#frontend-routes we are shown the following javascript example:

```js
export const extend = [
  new Extend.Routes()
    .add('/users', 'acme.users', <UsersPage />)
];
```

However in the source https://github.com/flarum/core/blob/master/js/src/common/extend/Routes.js we can see the signature:

```js
add(name, path, component) {
    // [...]
}
```

This seems to be confirmed by me implementing this in my extension. I had to pass the name first and path second.

This differs from the parameter order in PHP where path is actually first and name second.

If someone could go through the documentation and check that we show the correct way to call it each time, that would be great! Otherwise I'll do it when I find some time.

**Comment by clarkwinkelmann** [comment]
Additional note: those examples will also need updating for beta 14 and the Mithril routing changes (`<UsersPage />` => `UsersPage`)

Maybe @askvortsov1 will want to take care of it in #124

**Comment by askvortsov1** [comment]
Yeah all references to those have been replaced with equivalent non-JS-extender code (that works for b14) in #124. JS extenders are worth revisiting eventually, but probably not until a v2 of flarum.
