### ISSUE TITLE
Add Flarum logo

### ISSUE THREAD

**Issue by lhsazevedo** [flarum/docs#136]
Add Flarum logo to the navigation bar.

After researching some references, I came up with two proposals that follow below.

## A) Brand mark
Inspired by [Vue.js 3 documentation](https://v3.vuejs.org/) (VuePress).
Pull Request: https://github.com/flarum/docs/pull/137

Preview:
![brand-mark](https://user-images.githubusercontent.com/7695608/96204436-b5f23000-0f3a-11eb-9714-db8be33084ce.png)

## B) Docs logo
Inspired by [Netlify documentation](https://docs.netlify.com) (VuePress).
Pull Request: https://github.com/flarum/docs/pull/138

Preview:
![flarum-docs-print](https://user-images.githubusercontent.com/7695608/96204638-331da500-0f3b-11eb-854f-4f96cf1393c3.png)

**Comment by tankerkiller125** [comment]
I'm personally a fan of version B

**Comment by askvortsov1** [comment]
Both look awesome, but I'm also leaning B. Thanks so much for putting this together!

**Comment by lhsazevedo** [comment]
Glad to contribute :)
