### ISSUE TITLE
0.1.0-beta.8 upgrade/changelog

### ISSUE THREAD

**Issue by luceos** [flarum/docs#14]
This issue houses all changes for beta 8. We can split the list up into different sections:

- Webmaster (people installing and upgrading Flarum)
- Developer (people maintaining a Flarum extension)

# Webmaster

- The minimum PHP version will now be 7.1. It used to be 5.6.
- The minimum MySQL version will now be 5.6. It used to be 5.5.
- The skeleton `flarum/flarum` was updated:
  - public folder added
  - api.php and admin.php are removed
  - the .htaccess now directs all requests to non-existing files to index.php
  - The akismet extension has been [unbundled](https://github.com/flarum/flarum/commit/088fdb41109d39194903ec91458c4b6353a8179d).
- New `discussion.hidePosts` permissions, enabled by default (and via upgrade) for moderators.
  - Custom groups might need to be adapted as well.
  - See flarum/core#1387 and flarum/core#1466.

# Developer

- Pretty much all namespaces changed.
- Events were moved from one global Event namespace to their respective namespaces, eg `Flarum\Event\UserWillBeSaved` > `Flarum\User\Event\Saving`
- FloodGate has been made extensible

**Comment by franzliedke** [comment]
Here's the (probably 95% complete and correct) list of namespace changes: https://discuss.flarum.org/d/6572-help-us-namespace-changes

**Comment by tobscure** [comment]
We should also provide an official version of the [script](https://discuss.flarum.org/d/6573-convert-your-beta-7-compatible-extension-to-work-on-beta-8) that @CDK2020 made. It needs a few tweaks – I realise I should've done that as I was upgrading all of our extensions, but forgot 😓 Even so, it's far better than nothing.

**Comment by tobscure** [comment]
https://gist.github.com/tobscure/55e7c05c95404e5efab3a9e43799d375

Made one update to it so far

**Comment by luceos** [comment]
- [ ] Database changes (developers)

**Comment by franzliedke** [comment]
[This documentation PR](https://github.com/flarum/flarum.github.io/pull/65) should probably be reverted for the release.

**Comment by franzliedke** [comment]
After [this commit](https://github.com/flarum/core/commit/ba96f311a960314104becc716cd3dc7b5291cc6d), we can probably remove the requirement on the fileinfo extension, if I am not mistaken.

**Comment by luceos** [comment]
icons;

- with the `icon()` helper now need full declaration from `cog` to `far fa-cog`
- in elements that have an `icon` property need the same new declaration (buttons with images fi)
- no longer support font awesome 4, all icons have to be from 5 (free version)
- this also means the `-o` "open" modifier on some icons has been removed for the preferred strong, regular, light alternatives

**Comment by luceos** [comment]
akismet was unbundled
