### ISSUE TITLE
Version constraints for beta.14

### ISSUE THREAD

**Issue by matteocontrini** [flarum/docs#143]
The getting started page in the Extend docs still suggests to use `>=0.1.0-beta.12 <0.1.0-beta.14` as the `flarum/core` version constraint.

It should be updated now that beta.14 has been released.

**Comment by askvortsov1** [comment]
Thanks!

**Comment by matteocontrini** [comment]
I think this sentence should be updated as well:

>NOTE: Flarum 0.1.0-beta.14 is scheduled for breaking changes as part of a rewrite of the entire frontend, we recommend the current compatibility scheme for now.

**Comment by askvortsov1** [comment]
Fixed, thanks!
