### ISSUE TITLE
New section: "Shared hosts"

### ISSUE THREAD

**Issue by franzliedke** [flarum/docs#16]
The default skeleton now requires pointing the webserver root to the public/ folder. This is not possible on most shared hosts.

For them, we need some additional instructions, they will mostly consist of:
- adding/moving one file (ping me for the exact code - I will do my best to keep the changes as small as possible)
- some necessary security-hardening (preventing access to certain files and directories, see flarum/core#692)

**Comment by luceos** [comment]
This also applies for using Flarum in a subdirectory, although the instructions could be made generic enough to apply to:

- public_html (common in most shared hosts)
- subdirectory
