### ISSUE TITLE
Document local extenders

### ISSUE THREAD

**Issue by askvortsov1** [flarum/docs#195]
Followup to #194 

@luceos did you have an article about this somewhere on Discuss, or am I misremembering?

**Comment by luceos** [comment]
I have some information scattered and a repo with just one example.

**Comment by franzliedke** [comment]
We started with local extenders before we dive into full extensions: https://docs.flarum.org/extend/start.html#hello-world

**Comment by askvortsov1** [comment]
> We started with local extenders before we dive into full extensions: https://docs.flarum.org/extend/start.html#hello-world

Nice catch! Added a link and a blurb to the placeholder page in the PR.
