### ISSUE TITLE
Make installation page more user-friendly

### ISSUE THREAD

**Issue by OrdinaryJellyfish** [flarum/docs#23]
I think the installation page looks a bit empty having just installation guides for Ubuntu and CentOS. I'd like to make the installation page hold a bit more information considering the stability and just the basic commands and configuration needed, and link to the guides before that (but after the stability warnings) in case the user is in fact using a VPS or dedicated server. I'd also like to modify the CentOS and Ubuntu installation guides a bit to make it a little more understandable and less cluttered. May I do this (sorry, this is kind of my first time doing something like this, so not exactly sure how it works)?

**Comment by OrdinaryJellyfish** [comment]
I just found an error in the Ubuntu installation guide: Ubuntu Server 16.04 is `php7.0`, not `php7.2`.

**Comment by OrdinaryJellyfish** [comment]
Ok, looking over at the docs, I see it needs a lot more work than just prettifying the installation page.

**Comment by CDK2020** [comment]
@OrdinaryJellyfish can you list some improvements you'd like to see?

**Comment by OrdinaryJellyfish** [comment]
@CDK2020 
* Primary installation page to hold more information and be more user-friendly overall
* OS installation guides to be more informative and understandable and have the full MySQL setup and possibly have some kind of guide to using Let's Encrypt
* Homepage to hold more information
* Sidebar
* Better header links
* etc, etc

**Comment by CDK2020** [comment]
@OrdinaryJellyfish this isn't meant to look pleasing yet. This is just the skeleton for us to work on. Aka the UX isn't implemented on this repo yet.

**Comment by OrdinaryJellyfish** [comment]
Yes, yes, I know, it just seems your time is slowly running out since the
beta 8 milestone only has 6 things left (I know they're major, but still).
The documentation still needs a whole lot of work to be done.

**Comment by franzliedke** [comment]
@OrdinaryJellyfish Absolutely! You are more than welcome to propose changes directly in small PRs. It is also very wise to ask whether there is interest for some of these changes. Which you did here. 👍

**Comment by OrdinaryJellyfish** [comment]
Okay, thanks!

**Comment by CDK2020** [comment]
#24 is the relevant PR

**Comment by franzliedke** [comment]
Can this be considered done then?

**Comment by OrdinaryJellyfish** [comment]
I suppose.
