### ISSUE TITLE
Rename repo to "flarum-docs"

### ISSUE THREAD

**Issue by wion** [flarum/docs#3]
Any chance? It would be nice to have more distinction in my local repo names against other docs projects I contribute to, which generally go by "{project}-docs" -- "docs" by itself is a little too generic.

**Comment by Luceos** [comment]
It's quite easy to fork and then rename your private fork. On your local system you can also do a clone that targets a specific directory. The reasoning behind not using the prefix is that the prefix was/is meant for extensions, which this is not.
