### ISSUE TITLE
Running the Project on the localhost

### ISSUE THREAD

**Issue by DursunCanPoyraz** [flarum/docs#343]
How can I see the changes I made in my own repository on the `localhost`? Can you explain in detail? with npm?

PR: https://github.com/flarum/docs/pull/334

**Comment by datitisev** [comment]
Run `npm run dev`.

**Comment by DursunCanPoyraz** [comment]
@datitisev When I enter this command after opening the folder with `cmd`, it gives an error.

**Comment by davwheat** [comment]
What error do you get...?

**Comment by DursunCanPoyraz** [comment]
Do I need to install npm on localhost? this error comes up when there is no installation in other things.

```
C:\Users\user\Desktop\GitHub\docs>npm run dev
'npm' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by datitisev** [comment]
You need Node.JS & NPM installed, yes. This is a nodejs project.

**Comment by askvortsov1** [comment]
Feel free to reopen if you're still running into issues
