### ISSUE TITLE
Switch to Docusaurus

### ISSUE THREAD

**Issue by askvortsov1** [flarum/docs#369]
I think we should consider switching to Docusaurus instead of VuePress for our docs system. A few advantages:

- Designed to work with [crowdin](https://docusaurus.io/docs/i18n/crowdin), which we want to use
- Has a scalable way to manage [multiple types of docs](https://stackoverflow.com/questions/60783595/is-there-a-way-to-have-two-docs-in-docusaurus-2) for extend, admin, user, core dev, etc. We'll want to add more of these, so this flexibility is handy.
- Much less config needed for [internationalization](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#i18n)
- Dark mode!
- Built-in ToC
- Powered by React, which is pretty cool!
- Supports a landing page, as well as blog/static pages if we wanted that
- Has great versioning support for when we move to v2

**Comment by tankerkiller125** [comment]
I'm going to close this as we have in fact switched to Docusaurus successfully and have been using it for several months now.
