### ISSUE TITLE
"Edit this page" link doesn't work for index pages

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/docs#37]
If you click "Edit this page" at https://flarum.org/docs/extend/ you will be taken to https://github.com/flarum/docs/edit/master/docs/extend/README.md instead of https://github.com/flarum/docs/edit/master/docs/extend/index.md

Same for https://flarum.org/docs/

**Comment by datitisev** [comment]
Maybe we should rename the files to README.md then... there's no downside to that and we wouldn't have to do weird stuff with Vuepress.

**Comment by tobscure** [comment]
PR welcome!
