### ISSUE TITLE
Missing Flarum's own utilities in Troubleshooting page

### ISSUE THREAD

**Issue by jordanjay29** [flarum/docs#73]
The Troubleshooting page does not contain a description of `php flarum info` or how to use it/what it does. This is our best diagnostic utility for troubleshooting, so we might as well promote it in our own docs pages.

**Comment by franzliedke** [comment]
Good point. :+1: 

When doing support, have you recently come across other questions that `php flarum info` could answer?

**Comment by franzliedke** [comment]
Okay, so it currently fulfills all your needs, if I understand you correctly. Because that was my question. :wink:
