### ISSUE TITLE
Assets recompilation only when debug mode is on

### ISSUE THREAD

**Issue by relax4o** [flarum/docs#77]
Hello,

Nowhere in the Contribution section was mentioned how to use the locally compiled assets. I was busting my head figuring this out and finally I realised that during development the `debug` mode in the configuration file must be set to `true`.

I haven't investigated what does `debug: true` includes as debugging as I am fan of the actual xdebug debugging but I never thought that would be something that relates so much to the assets, so I've never turned on this option.
Finally I turned it on and realised that this is a key option to make the assets to get recompiled on the page.

I think this part is very important to be documented for new contributors coming to help Flarum.

~~Also, when working on extensions' js files, I think that `npm link ../../core/js` is enough.~~

**Comment by datitisev** [comment]
It _is_ mentioned in the "Frontend Development" part of the extension documentation (https://flarum.org/docs/extend/frontend.html#asset-registration). We might want to move it somewhere better.
![image](https://user-images.githubusercontent.com/6401250/64909850-13d09a80-d6df-11e9-8693-f230efbe8d3f.png)

---

> Also, when working on extensions' js files, I think that `npm link ../../core/js` is enough.

Sorry? Can you elaborate on what you mean by this ?

**Comment by relax4o** [comment]
@datitisev in my opinion, definitely needs a better place to be put on. Since I haven't started working on extension (or I don't even know if I am going to) and want to fix just bug in the assets(either the core or any other existing extension) I probably won't read the extension section.
I mean, I took a glance and apparantly I missed that.

The best place would be [here](https://flarum.org/docs/contributing.html#development-setup). It doesn't make any sense if I know how to or where to run `npm run dev` without knowing how exactly this compiled assets will be reflected on the page.

> Sorry? Can you elaborate on what you mean by this ?
We can skip this. I don't know why I thought `npm link ../../core/js` would be enough without realising that an extension might include other packages which needs to be installed.
