### ISSUE TITLE
Amazon SES instructions

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/docs#83]
In order to use the SES driver, the `aws/aws-sdk-php` package is needed.

In its time, Flagrow Mail Drivers had the following line in its README:

>  Before configuring the SES driver you need to install the Amazon SDK with `composer require aws/aws-sdk-php:~3.0`.

We should add it somewhere in the Flarum docs, though I don't know which place makes sense.

We could also make it a message inside Flarum itself when you select the SES driver though I'm not sure it's worth the hassle.

**Comment by franzliedke** [comment]
Hmm, that sucks a bit in terms of usability. Should we extract SES to an extension instead, that brings along the SDK via its own dependencies?

**Comment by clarkwinkelmann** [comment]
Yes a separate extension could make sense. It wouldn't contain much code, but that way people could install it like any other extension.

**Comment by franzliedke** [comment]
Okay, let's do that then.

Closing in favor of flarum/core#1986.
