### ISSUE TITLE
Multi-language support?

### ISSUE THREAD

**Issue by Littlegolden** [flarum/docs#87]
I can translate documents into Chinese. Is there any plan to enable multi-language vuepress documents?

**Comment by OrdinaryJellyfish** [comment]
VuePress has built-in support for internationalization: https://vuepress.vuejs.org/guide/i18n.html

**Comment by datitisev** [comment]
I think we agreed internally on enabling internationalization when we are sure the translated documentation will be kept up-to-date. I cannot offer more details on this topic because I do not remember them 🙂.

**Comment by luceos** [comment]
@datitisev if you can enable it and offer some simple instructions what to add where we can allow @Littlegolden to start translating. Do not translate docs about the frontend extending yet though..

**Comment by datitisev** [comment]
What we'd have to do is add a `locales` key to `.vuepress/config.js`.

This is their example on their docs:

```js
module.exports = {
  locales: {
    // The key is the path for the locale to be nested under.
    // As a special case, the default locale can use '/' as its path.
    '/': {
      lang: 'en-US', // this will be set as the lang attribute on <html>
      title: 'VuePress',
      description: 'Vue-powered Static Site Generator'
    },
    '/zh/': {
      lang: 'zh-CN',
      title: 'VuePress',
      description: 'Vue 驱动的静态网站生成器'
    }
  }
}
```

Then we could create the documentation in a `docs/zh` folder (if we followed this example).

Default texts in the theme could then be changed with `themeConfig.locales`

```js
module.exports = {
  locales: { /* ... */ },
  themeConfig: {
    locales: {
      '/': {
        // text for the language dropdown
        selectText: 'Languages',
        // label for this locale in the language dropdown
        label: 'English',
        // Aria Label for locale in the dropdown
        ariaLabel: 'Languages',
        // text for the edit-on-github link
        editLinkText: 'Edit this page on GitHub',
        nav: [
          { text: 'Nested', link: '/nested/' , ariaLabel: 'Nested' }
        ],
        sidebar: {
          '/': [/* ... */],
          '/nested/': [/* ... */]
        }
      },
      '/zh/': {
        selectText: '选择语言',
        label: '简体中文',
        editLinkText: '在 GitHub 上编辑此页',
        nav: [
          { text: '嵌套', link: '/zh/nested/' }
        ],
        sidebar: {
          '/zh/': [/* ... */],
          '/zh/nested/': [/* ... */]
        }
      }
    }
  }
}
```

**Comment by Littlegolden** [comment]
The CSUR Documentations (with four languages) can be an example. I referenced Flarum's documentation configuration during the build.

**Comment by franzliedke** [comment]
To be honest, I still have my doubts that we will be able to keep this up to date with changes - especially not when no core team member speaks the respective language (AFAIK).

**Comment by datitisev** [comment]
@franzliedke @KyrneDev speaks Chinese. He's not very active atm though.

**Comment by askvortsov1** [comment]
I think even a basic offering with a very very clear and sternly worded disclaimer is better than nothing.

**Comment by franzliedke** [comment]
Oh, cool! Then it could work, I guess.

I still have doubts as previous attempts at internationalization like that in other projects did not work for me. Maybe Flarum has now reached a size where where this could work, I do not know.

One other thing: the docs are still expected to change (or at least grow) considerably until stable, so maybe that would be a better moment to start such an initiative?

But given I haven't really been involved with this topic much, I guess I am not particularly constructive right now :sweat_smile:, so I can certainly live with what you guys decide.

**Comment by tankerkiller125** [comment]
@franzliedke We seem to have a large number of highly dedicated translators for Flarum core and the many community extensions. I have a feeling that if we enable translations on the docs and broadcast that we're open to PRs with translations that we would quickly get flooded with new PRs filling in that gap.

**Comment by franzliedke** [comment]
> we would quickly get flooded with new PRs

:scream: :speak_no_evil: 

Sorry, you triggered me there. :shrug: :wink:

**Comment by askvortsov1** [comment]
Sorry Franz 😔
